# Generated by Django 5.2.3 on 2025-07-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("REALTIME_RECOGNITION", "孤立手语识别"),
                            ("IMAGE_RECOGNITION", "中文图片识别"),
                            ("VIDEO_RECOGNITION", "中文视频识别"),
                            ("ANIMATION_GENERATION", "手语动画生成"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                ("lang", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
